### ISSUE TITLE
/scripts/run_acceptance_tests_local.sh and /scripts/run_acceptance_tests.sh take different env variables

### ISSUE THREAD

**Issue by shubhaat** [cloudfoundry-incubator/disaster-recovery-acceptance-tests#17]
During my testing, I tried to run /scripts/run_acceptance_tests.sh and /scripts/run_acceptance_tests_local.sh. I could run neither

/scripts/run_acceptance_tests_local.sh expects a BOSH_CA_CERT 
and
 /scripts/run_acceptance_tests.sh expects a BOSH_CERT_PATH for the director-ca-cert.

**Comment by edwardecook** [comment]
@shubhaat our tests use the cert via a file path, and `run_acceptance_tests_local.sh` writes a cert to a path and then calls `run_acceptance_tests.sh` with that path as a environment variable.

We think you ought to be able to use `run_acceptance_tests_local.sh`. Therefore you don't need to bother with `run_acceptance_tests.sh`, which is a script intended to be called by other scripts, not humans. Let's discuss why `run_acceptance_tests_local.sh` is problematic for you on the call today. We don't want to change `run_acceptance_tests.sh` and our DRATS code to use `BOSH_CA_CERT` internally at this point, because lots of teams are using it, and this cause problems for them.

cc @flangewad

**Comment by shubhaat** [comment]
In that case your documentation is not correct? It should say run /scripts/run_acceptance_tests_local.sh here under running drats: https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests

**Comment by edwardecook** [comment]
@shubhaat it's definitely not correct, I've created https://www.pivotaltracker.com/n/projects/1662777 (which is next on the backlog) to encompass that and some formatting issues

**Comment by edwardecook** [comment]
@shubhaat README is now recommending /scripts/run_acceptance_tests_local.sh, closing this story.
