### ISSUE TITLE
What is proper value to GOPATH to run DRATS with environment variables?

### ISSUE THREAD

**Issue by eujungkim** [cloudfoundry-incubator/disaster-recovery-acceptance-tests#29]
I tried to run DRATS with Environment Variables in local.
I checked out disaster-recovery-acceptance-tests and set environments and run script like below.

/disaster-recovery-acceptance-tests# ./scripts/run_acceptance_tests_local.sh
./scripts/run_acceptance_tests_local.sh: line 14: GOPATH: parameter null or not set

Error occurred because GOPATH is not set.
What is proper value to GOPATH?

**Comment by alamages** [comment]
Hi Eujung Kim

In older versions of Golang it was required to set $GOPATH to configure your go workspace. It appears that the latest go tool has defaults.

You can check your current $GOPATH by running:

```bash
$ go env GOPATH
```

Please follow these instructions for [Setting GOPATH](https://github.com/golang/go/wiki/SettingGOPATH).

In order to run DRATS this repo must be in the $GOPATH. You can use the go tool to clone this repo into your $GOPATH:

```bash
# Use go tool to clone repo into $GOPATH/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests

$ go get github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests
```

Best wishes
Emmanouil and @jamesjoshuahill
